### ISSUE TITLE
can't export annotation image with more than 2 images

### ISSUE THREAD

**Issue by johnzw** [kyamagu/js-segment-annotator#14]
when I put more than 2 images in the imageURLs field in the json file, I can only view the first two images when I visit `index.html`. I can view all the other images by clicking "Next" though.

The problem is: I can annotate **the first two images** and export the annotation pictures. But as for **the other images**, I am able to annotate the image, but **not** able to export it: There is no response when I click the "export" button.

How can I solve this issue?

p.s. The browser I use is Firefox(v42.0 Mac). `index.html` appeared to be blank with Chrome(v47.0 Mac) and Safari(v9.0).

Thanks,
john

**Comment by kyamagu** [comment]
@johnzw How did you prepare your data JSON file? Does it look similar to `data/example.json`?

**Comment by jorgyz** [comment]
I was having this issue as well. To fix it, open your json file and add an entry in "annotationURLs" corresponding to each of the entries in imageURLs. It does not matter that the annotation images do not exist -- the script will just use the file names you enter in annotationURLs as the file name for the exported images.  The export button should now work.

**Comment by rosdyana** [comment]
Hi,

In case the images more than 10 and it will be not good to write one by one, I wrote a script to generate json here : https://gist.github.com/rosdyana/1344d8dc9380c34e9128381d72b8830e
