### ISSUE TITLE
Denoising button / Change color 

### ISSUE THREAD

**Issue by Timo-hab** [kyamagu/js-segment-annotator#17]
Hi kyamagu

Thank you for your cool labeltool! I did not get the function of the denoising-button? What is it doing?

Can you please tell me in which file I can change the colors for the labels? 
Thank you in advance!

Best
Timo

**Comment by kyamagu** [comment]
@Timo-hab Check [here](https://github.com/kyamagu/js-segment-annotator/blob/master/js/main.js#L12) for how to create a colormap.

The denoising button removes small annotations (e.g., 1-pixel label) by [finding dominant label in the neighboring pixels](https://github.com/kyamagu/js-segment-annotator/blob/master/js/image/morph/max-filter.js).
