### ISSUE TITLE
Annotated image are mostly zero pixel value

### ISSUE THREAD

**Issue by eliethesaiyan** [kyamagu/js-segment-annotator#24]
@kyamagu i used this tool for annotating my images for caffe-segnet,i first saw that all images are darker(you can hardly notice edges of annotated objects) but i thought on pixel level it might be different,but after checking in matlab,the whole image is almolt zero pixel.i would be happy if you could point out what i am doing wrong.thx

**Comment by kyamagu** [comment]
@eliethesaiyan Check `unique(image)` to see if the pixels are all zero or not.

**Comment by eliethesaiyan** [comment]
@kyamagu ,it gave me  0  1
