### ISSUE TITLE
How to code RGB and index information (8b)

### ISSUE THREAD

**Issue by marticsvk** [kyamagu/js-segment-annotator#25]
Hi @kyamagu 

thank you for such a nice tool to annotate pictures. I'd like to ask if it is possible to do following:

I already customized your tool and add 3 classes (Dress, Trousers, Jacket) as can be seen on this picture:
![33](https://cloud.githubusercontent.com/assets/25150060/24476402/6d304aa6-14d3-11e7-8253-c1bb8fb2c3cc.png)
On the next picture below is annotated image from Pascal VOC 2012 for segmentation, containing RGB information + index for object and also the same for background.
![11](https://cloud.githubusercontent.com/assets/25150060/24474741/eb5af580-14cd-11e7-9eb4-3101e223c8de.jpg)

However, output from JS segmenter looks like this:
![22](https://cloud.githubusercontent.com/assets/25150060/24474803/1680b790-14ce-11e7-8f63-185cac5f333a.jpg)

If it is possible, could you please tell us on this example how to convert image from 32b to 8b and how to code the demanded information into image as it is in attached annotated VOC Pascal above. 
E.g.
for background --> index 0 and RGB{0 0 0}
for jacket --> index 3 and RGB{192 128 0}.

Thank you in advance, much appreciated!

**Comment by kyamagu** [comment]
@marticsvk Check [README](https://github.com/kyamagu/js-segment-annotator#matlab-tips).

**Comment by HardTaskToFindAName** [comment]
Unfortunately I have no MATLAB. Can you describe how it is possible to convert the annotations with python? I trying to solve the problem for hours now but not really get it. Is it possible to directly load the 
32b png annotations with python and then convert it properly?

**Comment by kyamagu** [comment]
@HardTaskToFindAName Just updated the [README](https://github.com/kyamagu/js-segment-annotator#python-tips). Please check.
