### ISSUE TITLE
Possible to update the annotation image after editing?

### ISSUE THREAD

**Issue by ghost** [kyamagu/js-segment-annotator#27]
I wanted to know if it is possible to have a save option which will update the annotation image in the data/annotations/ folder. 

If this is possible, where should I add this functionality?

**Comment by kyamagu** [comment]
@anandcu3work I believe it is very difficult to write to a local file system using Javascript. [See this.](https://developer.mozilla.org/en-US/docs/Web/API/File_and_Directory_Entries_API)
