### ISSUE TITLE
Tool crashes on loading Pre-Annotated Images

### ISSUE THREAD

**Issue by anandcu3** [kyamagu/js-segment-annotator#29]
Hi @kyamagu ,

Thank you for sharing this project.

I'm trying to use custom annotation images and I've created the JSON file accordingly. The tool loads up the relevant classes color-coded over the image. But when I try to correct some segmentation the tool stops working and the following error is printed in the console.

Browser Console Dump
[localhost-1505715475195.txt](https://github.com/kyamagu/js-segment-annotator/files/1309831/localhost-1505715475195.txt)

SampleJSON
![untitled](https://user-images.githubusercontent.com/13032916/30531015-ff7bf938-9c68-11e7-92aa-0d6868966c66.png)
)

Sample Browser Screenshot
![untitled](https://user-images.githubusercontent.com/13032916/30530826-a0522302-9c67-11e7-9c03-0c69a87baf3f.png)

**Comment by kyamagu** [comment]
@anandcu3 Do you change the set of labels? The crash happens because the annotation data seem to contain a label index outside of the given set.

https://github.com/kyamagu/js-segment-annotator/blob/master/js/app/edit.js#L476

**Comment by anandcu3** [comment]
@kyamagu I did not change the labels but the image was generated by a inaccurate ML algorithm . But I made sure the value in the annotations are between 0 and n (num of classes). 1->Sky, 2->Building etc..

**Comment by kyamagu** [comment]
@anandcu3 You have to have `0` index (usually background) in the label set.

**Comment by anandcu3** [comment]
@kyamagu  Isn't that Sky in my case ?

**Comment by kyamagu** [comment]
@anandcu3 You are mapping Sky to `1`, not `0`.

**Comment by kyamagu** [comment]
If you really intend to use Sky for `0`, then I assume there is invalid integer index in the incomplete data.

**Comment by anandcu3** [comment]
I'm sorry I made a mistake in my earlier message. I have mapped sky-->0, building->1 and so on..

**Comment by kyamagu** [comment]
@anandcu3 Ok, then first check unique set of index values in the annotation PNG.

**Comment by anandcu3** [comment]
The other question is are there any specifications to the annotations image format that has to be taken care of ..

**Comment by kyamagu** [comment]
@anandcu3 The format is specified in [README](https://github.com/kyamagu/js-segment-annotator#python-tips).

**Comment by anandcu3** [comment]
`a=cv2.imread("data/annotations/00001.png")`
`print(numpy.unique(a))`

returned

`array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=uint8)`

**Comment by kyamagu** [comment]
@anandcu3 The PNG is RGB-encoded UINT32 and cannot be read just by `cv2.imread`. Make sure all the index values are properly formatted. Other than that, you can always open up browser javascript console to inspect values.

**Comment by anandcu3** [comment]
@kyamagu  I've an array with the same shape of an image. Each pixel representing the class label. How do I encode this? I've been trying to use the encode portion of the code in README but I get this error.

`Traceback (most recent call last):
  File "D:\anand\anaconda3\lib\site-packages\PIL\Image.py", line 2167, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3, 3), '|u1')`

`During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\anand\anaconda3\lib\site-packages\PIL\Image.py", line 2170, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type`

**Comment by kyamagu** [comment]
@anandcu3 Convert the array to uint32 first, then try encoding with the code example.

**Comment by anandcu3** [comment]
@kyamagu  Thank you very much. It worked. :)
