### ISSUE TITLE
How to export the annotated png as json not png. The same way as it is exporting in http://clothingparsing.com/#

### ISSUE THREAD

**Issue by defaultcute12** [kyamagu/js-segment-annotator#32]

**Comment by kyamagu** [comment]
You can use `export()` method of the annotator.
https://github.com/kyamagu/js-segment-annotator/blob/master/js/helper/segment-annotator.js#L172

**Comment by defaultcute12** [comment]
Is it like using fabric.js - tojson() instead of todataurl() ?

**Comment by defaultcute12** [comment]
I was able to fetch json ?
But i can only get image : data
is there any additional work needed to be done to fetch 
{"name":"bag","color":[255,0,0]}
this data?

**Comment by defaultcute12** [comment]
I am still not able to fetch label/color pair.
Any help will be appreciated
Thanks a lot !!

**Comment by kyamagu** [comment]
@defaultcute12 You can get `colormap` property for colors

https://github.com/kyamagu/js-segment-annotator/blob/master/js/helper/segment-annotator.js#L25

You probably already defined your colormap/labels outside of the annotator. The annotator only keeps integer labels.

https://github.com/kyamagu/js-segment-annotator/blob/master/js/main.js#L28

**Comment by defaultcute12** [comment]
Thanks a lot for the help.

Regards,
Mallu

**Comment by defaultcute12** [comment]
Thanks a lot for all the help.
Can I ask one last question.
Is it possible to get pixels associated with a color in this tool ?

**Comment by kyamagu** [comment]
Check [README](https://github.com/kyamagu/js-segment-annotator#python-tips).

**Comment by defaultcute12** [comment]
Thanks !
