### ISSUE TITLE
Erase functionality

### ISSUE THREAD

**Issue by Abdul-Ghani** [kyamagu/js-segment-annotator#39]
I want to add an Erase button which erases any selection previously done.
I used an button which when clicked calls a function very similar to the function responsible for Brush, which is:
```javascript
for (var y = -1 * brushSize; y <= brushSize; y++) {
    for (var x = -1 * brushSize; x <= brushSize; x++) {
      if (x * x + y * y > brushLimit) continue;
      var offset =
        4 *
        ((pos[1] + y) * this.layers.visualization.canvas.width + (pos[0] + x));
      offsets.push(offset);
      labels.push(label);
    }
  }
  annotator._updateAnnotation(offsets, labels);
```
with one difference:
```javascript
 labels.push(label);
```
The last line inside the for loop I've hardcoded 0 being pushed into labels.
```javascript
 labels.push(0);
```
0 represents the background white color so on clicking the Erase button and selecting any area within a selection, it looks like stuff is being erased since the color of the label gets replaced by the background.
But in truth this isn't actually erasing anything, just continues to add label with white background. So when I export it, the erased area expectedly still shows up.

Any pointers on how to delete previously selected area?

**Comment by kyamagu** [comment]
Why not just choose current label=0 (`annotator.currentLabel = index;`) and use any of the desired tool?

**Comment by Abdul-Ghani** [comment]
>it looks like stuff is being erased since the color of the label gets replaced by the background.
But in truth this isn't actually erasing anything, just continues to add label with white background. So when I export it, the erased area expectedly still shows up.

What I need to do is unselect an area, using current label 0 is still drawing label with color white.

**Comment by kyamagu** [comment]
Do you mean [`undo` functionality](
https://github.com/kyamagu/js-segment-annotator/blob/master/js/helper/segment-annotator.js#L78)
or [`fill` existing labels](
https://github.com/kyamagu/js-segment-annotator/blob/master/js/helper/segment-annotator.js#L115)?
Default label for every pixel is 0.

>

**Comment by Abdul-Ghani** [comment]
Undo is not what I want, I may want to erase one particular segment of labelling that I've done, I wouldn't want to delete all the other subsequent labelling I've done after it.
And with fill(), there is
```javascript
        annotationData = this.layers.annotation.imageData.data;
```
How am I to update imageData of the annotation layer?, so that the updated image data is assigned to annotationData here.

One solution I thought of was to store a list of all the [x,y] coordinates that he's selected clicked for and do a clearRect() of annotation layer for each of them. What do you think?

**Comment by kyamagu** [comment]
@Abdul-Ghani There is no notion of segment or piece in brush tool. Every stroke directly paints pixels.

**Comment by Abdul-Ghani** [comment]
Right, and I want to do an eraser which can delete any labelling selection done by either polygon or brush or superpixel selection. 
Can you help me by explaining the offset line here? (https://github.com/kyamagu/js-segment-annotator/blob/3f6e4be4ef2822b9946673f34920157cc3f89914/js/app/edit.js#L349)
```javascript
for (var y = -2; y <= 2; y++) {
      for (var x = -2; x <= 2; x++) {
        // it is circle bitches
        if ((x*x + y*y) > 7) continue;
        var offset = 4 * ((pos[1]+y) * this.layers.visualization.canvas.width + (pos[0]+x));
        offsets.push(offset);
        labels.push(label);
      }
    }
```
the line ```javascript         if ((x*x + y*y) > 7) continue;``` I think is used to check if the point is within the circle or outside. The line after that,
```javascript
        var offset = 4 * ((pos[1]+y) * this.layers.visualization.canvas.width + (pos[0]+x));
```
Can you help explain this above line?

**Comment by kyamagu** [comment]
Offset is the location within the memory buffer.

**Comment by Abdul-Ghani** [comment]
okay, how is it being calculated here? Can you explain the equation on the right side?

**Comment by kyamagu** [comment]
a buffer is row-major order, where pixels are arranged in RGBA order. `RGBARGBARGBA...`

**Comment by Abdul-Ghani** [comment]
Alright thanks @kyamagu this helped.
