### ISSUE TITLE
Some code using js-segment-annotator

### ISSUE THREAD

**Issue by AKSHAYUBHAT** [kyamagu/js-segment-annotator#6]
I am working on a code that uses this project, thought you might be interested. 

Repo: https://github.com/AKSHAYUBHAT/Vision
Demo: http://vision.akshaybhat.com/
![3](https://cloud.githubusercontent.com/assets/35259/7470172/94050838-f2e8-11e4-9057-74a422552091.gif)

**Comment by kyamagu** [comment]
Looks nice :) Good luck to your app

**Comment by AKSHAYUBHAT** [comment]
I have significantly improved it by using 1 nearest neighbor supervised labeling. 
http://segmentation.akshaybhat.com

**Comment by kyamagu** [comment]
@AKSHAYUBHAT Nicely done. A few comments on your project.

 * The default screen size looks too big for everybody. Fixed canvas size will be an issue if targeting at generic image editing.
 * Perhaps having a default image is good for a demo.

The `js-segment-annotator` got a major update recently, but you can continue using the slic codebase in the `v1.0` branch.
